/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioDesignRouteImport } from './routes/studio-design'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as InnovateRouteImport } from './routes/innovate'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersRegisterRouteImport } from './routes/partners.register'
import { Route as GuideStadiumAdvertisingCostsRouteImport } from './routes/guide.stadium-advertising-costs'
import { Route as ApiInnovateFeedRouteImport } from './routes/api/innovate-feed'
import { Route as ApiGenerateBillboardImageRouteImport } from './routes/api/generate-billboard-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicPiRfpsRouteImport } from './routes/api/public/pi-rfps'
import { Route as ApiPublicPiPartnersRouteImport } from './routes/api/public/pi-partners'
import { Route as ApiPublicPiCreativesRouteImport } from './routes/api/public/pi-creatives'
import { Route as ApiPublicPiContractsRouteImport } from './routes/api/public/pi-contracts'
import { Route as ApiPublicPiCompleteRouteImport } from './routes/api/public/pi-complete'
import { Route as ApiPublicPiCampaignsRouteImport } from './routes/api/public/pi-campaigns'
import { Route as ApiPublicPiBalanceRouteImport } from './routes/api/public/pi-balance'
import { Route as ApiPublicPiAuthRouteImport } from './routes/api/public/pi-auth'
import { Route as ApiPublicPiApproveRouteImport } from './routes/api/public/pi-approve'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const StudioDesignRoute = StudioDesignRouteImport.update({
  id: '/studio-design',
  path: '/studio-design',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovateRoute = InnovateRouteImport.update({
  id: '/innovate',
  path: '/innovate',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRegisterRoute = PartnersRegisterRouteImport.update({
  id: '/partners/register',
  path: '/partners/register',
  getParentRoute: () => rootRouteImport,
} as any)
const GuideStadiumAdvertisingCostsRoute =
  GuideStadiumAdvertisingCostsRouteImport.update({
    id: '/guide/stadium-advertising-costs',
    path: '/guide/stadium-advertising-costs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInnovateFeedRoute = ApiInnovateFeedRouteImport.update({
  id: '/api/innovate-feed',
  path: '/api/innovate-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateBillboardImageRoute =
  ApiGenerateBillboardImageRouteImport.update({
    id: '/api/generate-billboard-image',
    path: '/api/generate-billboard-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiRfpsRoute = ApiPublicPiRfpsRouteImport.update({
  id: '/api/public/pi-rfps',
  path: '/api/public/pi-rfps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiPartnersRoute = ApiPublicPiPartnersRouteImport.update({
  id: '/api/public/pi-partners',
  path: '/api/public/pi-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiCreativesRoute = ApiPublicPiCreativesRouteImport.update({
  id: '/api/public/pi-creatives',
  path: '/api/public/pi-creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiContractsRoute = ApiPublicPiContractsRouteImport.update({
  id: '/api/public/pi-contracts',
  path: '/api/public/pi-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiCompleteRoute = ApiPublicPiCompleteRouteImport.update({
  id: '/api/public/pi-complete',
  path: '/api/public/pi-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiCampaignsRoute = ApiPublicPiCampaignsRouteImport.update({
  id: '/api/public/pi-campaigns',
  path: '/api/public/pi-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiBalanceRoute = ApiPublicPiBalanceRouteImport.update({
  id: '/api/public/pi-balance',
  path: '/api/public/pi-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiAuthRoute = ApiPublicPiAuthRouteImport.update({
  id: '/api/public/pi-auth',
  path: '/api/public/pi-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiApproveRoute = ApiPublicPiApproveRouteImport.update({
  id: '/api/public/pi-approve',
  path: '/api/public/pi-approve',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/contracts': typeof ContractsRoute
  '/innovate': typeof InnovateRoute
  '/mcp': typeof McpRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/studio-design': typeof StudioDesignRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-billboard-image': typeof ApiGenerateBillboardImageRoute
  '/api/innovate-feed': typeof ApiInnovateFeedRoute
  '/guide/stadium-advertising-costs': typeof GuideStadiumAdvertisingCostsRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/pi-approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/pi-balance': typeof ApiPublicPiBalanceRoute
  '/api/public/pi-campaigns': typeof ApiPublicPiCampaignsRoute
  '/api/public/pi-complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi-contracts': typeof ApiPublicPiContractsRoute
  '/api/public/pi-creatives': typeof ApiPublicPiCreativesRoute
  '/api/public/pi-partners': typeof ApiPublicPiPartnersRoute
  '/api/public/pi-rfps': typeof ApiPublicPiRfpsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/contracts': typeof ContractsRoute
  '/innovate': typeof InnovateRoute
  '/mcp': typeof McpRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/studio-design': typeof StudioDesignRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-billboard-image': typeof ApiGenerateBillboardImageRoute
  '/api/innovate-feed': typeof ApiInnovateFeedRoute
  '/guide/stadium-advertising-costs': typeof GuideStadiumAdvertisingCostsRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/pi-approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/pi-balance': typeof ApiPublicPiBalanceRoute
  '/api/public/pi-campaigns': typeof ApiPublicPiCampaignsRoute
  '/api/public/pi-complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi-contracts': typeof ApiPublicPiContractsRoute
  '/api/public/pi-creatives': typeof ApiPublicPiCreativesRoute
  '/api/public/pi-partners': typeof ApiPublicPiPartnersRoute
  '/api/public/pi-rfps': typeof ApiPublicPiRfpsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/campaigns': typeof CampaignsRoute
  '/contracts': typeof ContractsRoute
  '/innovate': typeof InnovateRoute
  '/mcp': typeof McpRoute
  '/partner': typeof PartnerRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/studio-design': typeof StudioDesignRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-billboard-image': typeof ApiGenerateBillboardImageRoute
  '/api/innovate-feed': typeof ApiInnovateFeedRoute
  '/guide/stadium-advertising-costs': typeof GuideStadiumAdvertisingCostsRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/pi-approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/pi-balance': typeof ApiPublicPiBalanceRoute
  '/api/public/pi-campaigns': typeof ApiPublicPiCampaignsRoute
  '/api/public/pi-complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi-contracts': typeof ApiPublicPiContractsRoute
  '/api/public/pi-creatives': typeof ApiPublicPiCreativesRoute
  '/api/public/pi-partners': typeof ApiPublicPiPartnersRoute
  '/api/public/pi-rfps': typeof ApiPublicPiRfpsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/contracts'
    | '/innovate'
    | '/mcp'
    | '/partner'
    | '/sitemap.xml'
    | '/studio'
    | '/studio-design'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/partners'
    | '/api/chat'
    | '/api/generate-billboard-image'
    | '/api/innovate-feed'
    | '/guide/stadium-advertising-costs'
    | '/partners/register'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/pi-approve'
    | '/api/public/pi-auth'
    | '/api/public/pi-balance'
    | '/api/public/pi-campaigns'
    | '/api/public/pi-complete'
    | '/api/public/pi-contracts'
    | '/api/public/pi-creatives'
    | '/api/public/pi-partners'
    | '/api/public/pi-rfps'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/contracts'
    | '/innovate'
    | '/mcp'
    | '/partner'
    | '/sitemap.xml'
    | '/studio'
    | '/studio-design'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/partners'
    | '/api/chat'
    | '/api/generate-billboard-image'
    | '/api/innovate-feed'
    | '/guide/stadium-advertising-costs'
    | '/partners/register'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/pi-approve'
    | '/api/public/pi-auth'
    | '/api/public/pi-balance'
    | '/api/public/pi-campaigns'
    | '/api/public/pi-complete'
    | '/api/public/pi-contracts'
    | '/api/public/pi-creatives'
    | '/api/public/pi-partners'
    | '/api/public/pi-rfps'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/campaigns'
    | '/contracts'
    | '/innovate'
    | '/mcp'
    | '/partner'
    | '/sitemap.xml'
    | '/studio'
    | '/studio-design'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/partners'
    | '/api/chat'
    | '/api/generate-billboard-image'
    | '/api/innovate-feed'
    | '/guide/stadium-advertising-costs'
    | '/partners/register'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/pi-approve'
    | '/api/public/pi-auth'
    | '/api/public/pi-balance'
    | '/api/public/pi-campaigns'
    | '/api/public/pi-complete'
    | '/api/public/pi-contracts'
    | '/api/public/pi-creatives'
    | '/api/public/pi-partners'
    | '/api/public/pi-rfps'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  CampaignsRoute: typeof CampaignsRoute
  ContractsRoute: typeof ContractsRoute
  InnovateRoute: typeof InnovateRoute
  McpRoute: typeof McpRoute
  PartnerRoute: typeof PartnerRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  StudioDesignRoute: typeof StudioDesignRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateBillboardImageRoute: typeof ApiGenerateBillboardImageRoute
  ApiInnovateFeedRoute: typeof ApiInnovateFeedRoute
  GuideStadiumAdvertisingCostsRoute: typeof GuideStadiumAdvertisingCostsRoute
  PartnersRegisterRoute: typeof PartnersRegisterRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPiApproveRoute: typeof ApiPublicPiApproveRoute
  ApiPublicPiAuthRoute: typeof ApiPublicPiAuthRoute
  ApiPublicPiBalanceRoute: typeof ApiPublicPiBalanceRoute
  ApiPublicPiCampaignsRoute: typeof ApiPublicPiCampaignsRoute
  ApiPublicPiCompleteRoute: typeof ApiPublicPiCompleteRoute
  ApiPublicPiContractsRoute: typeof ApiPublicPiContractsRoute
  ApiPublicPiCreativesRoute: typeof ApiPublicPiCreativesRoute
  ApiPublicPiPartnersRoute: typeof ApiPublicPiPartnersRoute
  ApiPublicPiRfpsRoute: typeof ApiPublicPiRfpsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio-design': {
      id: '/studio-design'
      path: '/studio-design'
      fullPath: '/studio-design'
      preLoaderRoute: typeof StudioDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovate': {
      id: '/innovate'
      path: '/innovate'
      fullPath: '/innovate'
      preLoaderRoute: typeof InnovateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/register': {
      id: '/partners/register'
      path: '/partners/register'
      fullPath: '/partners/register'
      preLoaderRoute: typeof PartnersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/guide/stadium-advertising-costs': {
      id: '/guide/stadium-advertising-costs'
      path: '/guide/stadium-advertising-costs'
      fullPath: '/guide/stadium-advertising-costs'
      preLoaderRoute: typeof GuideStadiumAdvertisingCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/innovate-feed': {
      id: '/api/innovate-feed'
      path: '/api/innovate-feed'
      fullPath: '/api/innovate-feed'
      preLoaderRoute: typeof ApiInnovateFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-billboard-image': {
      id: '/api/generate-billboard-image'
      path: '/api/generate-billboard-image'
      fullPath: '/api/generate-billboard-image'
      preLoaderRoute: typeof ApiGenerateBillboardImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-rfps': {
      id: '/api/public/pi-rfps'
      path: '/api/public/pi-rfps'
      fullPath: '/api/public/pi-rfps'
      preLoaderRoute: typeof ApiPublicPiRfpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-partners': {
      id: '/api/public/pi-partners'
      path: '/api/public/pi-partners'
      fullPath: '/api/public/pi-partners'
      preLoaderRoute: typeof ApiPublicPiPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-creatives': {
      id: '/api/public/pi-creatives'
      path: '/api/public/pi-creatives'
      fullPath: '/api/public/pi-creatives'
      preLoaderRoute: typeof ApiPublicPiCreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-contracts': {
      id: '/api/public/pi-contracts'
      path: '/api/public/pi-contracts'
      fullPath: '/api/public/pi-contracts'
      preLoaderRoute: typeof ApiPublicPiContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-complete': {
      id: '/api/public/pi-complete'
      path: '/api/public/pi-complete'
      fullPath: '/api/public/pi-complete'
      preLoaderRoute: typeof ApiPublicPiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-campaigns': {
      id: '/api/public/pi-campaigns'
      path: '/api/public/pi-campaigns'
      fullPath: '/api/public/pi-campaigns'
      preLoaderRoute: typeof ApiPublicPiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-balance': {
      id: '/api/public/pi-balance'
      path: '/api/public/pi-balance'
      fullPath: '/api/public/pi-balance'
      preLoaderRoute: typeof ApiPublicPiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-auth': {
      id: '/api/public/pi-auth'
      path: '/api/public/pi-auth'
      fullPath: '/api/public/pi-auth'
      preLoaderRoute: typeof ApiPublicPiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-approve': {
      id: '/api/public/pi-approve'
      path: '/api/public/pi-approve'
      fullPath: '/api/public/pi-approve'
      preLoaderRoute: typeof ApiPublicPiApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  CampaignsRoute: CampaignsRoute,
  ContractsRoute: ContractsRoute,
  InnovateRoute: InnovateRoute,
  McpRoute: McpRoute,
  PartnerRoute: PartnerRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  StudioDesignRoute: StudioDesignRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateBillboardImageRoute: ApiGenerateBillboardImageRoute,
  ApiInnovateFeedRoute: ApiInnovateFeedRoute,
  GuideStadiumAdvertisingCostsRoute: GuideStadiumAdvertisingCostsRoute,
  PartnersRegisterRoute: PartnersRegisterRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPiApproveRoute: ApiPublicPiApproveRoute,
  ApiPublicPiAuthRoute: ApiPublicPiAuthRoute,
  ApiPublicPiBalanceRoute: ApiPublicPiBalanceRoute,
  ApiPublicPiCampaignsRoute: ApiPublicPiCampaignsRoute,
  ApiPublicPiCompleteRoute: ApiPublicPiCompleteRoute,
  ApiPublicPiContractsRoute: ApiPublicPiContractsRoute,
  ApiPublicPiCreativesRoute: ApiPublicPiCreativesRoute,
  ApiPublicPiPartnersRoute: ApiPublicPiPartnersRoute,
  ApiPublicPiRfpsRoute: ApiPublicPiRfpsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
