/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StudioDesignRouteImport } from './routes/studio-design'
import { Route as StudioRouteImport } from './routes/studio'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as RfpsRouteImport } from './routes/rfps'
import { Route as PartnerRouteImport } from './routes/partner'
import { Route as OptimizeRouteImport } from './routes/optimize'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as MarketplaceRouteImport } from './routes/marketplace'
import { Route as LocationsRouteImport } from './routes/locations'
import { Route as LedgerRouteImport } from './routes/ledger'
import { Route as InnovateRouteImport } from './routes/innovate'
import { Route as DisplayerRouteImport } from './routes/displayer'
import { Route as ContractsRouteImport } from './routes/contracts'
import { Route as CampaignsRouteImport } from './routes/campaigns'
import { Route as BookingsRouteImport } from './routes/bookings'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PartnersRegisterRouteImport } from './routes/partners.register'
import { Route as LocationsSlugRouteImport } from './routes/locations.$slug'
import { Route as GuideStadiumAdvertisingCostsRouteImport } from './routes/guide.stadium-advertising-costs'
import { Route as ApiInnovateFeedRouteImport } from './routes/api/innovate-feed'
import { Route as ApiGenerateBillboardImageRouteImport } from './routes/api/generate-billboard-image'
import { Route as ApiChatRouteImport } from './routes/api/chat'
import { Route as AdminPartnersRouteImport } from './routes/admin.partners'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as ApiPublicVerifyLedgerRouteImport } from './routes/api/public/verify-ledger'
import { Route as ApiPublicScreenPlaylistRouteImport } from './routes/api/public/screen-playlist'
import { Route as ApiPublicPiScreensRouteImport } from './routes/api/public/pi-screens'
import { Route as ApiPublicPiRfpsRouteImport } from './routes/api/public/pi-rfps'
import { Route as ApiPublicPiPartnersRouteImport } from './routes/api/public/pi-partners'
import { Route as ApiPublicPiOptimizeCreativeRouteImport } from './routes/api/public/pi-optimize-creative'
import { Route as ApiPublicPiCreativesRouteImport } from './routes/api/public/pi-creatives'
import { Route as ApiPublicPiContractsRouteImport } from './routes/api/public/pi-contracts'
import { Route as ApiPublicPiCompleteRouteImport } from './routes/api/public/pi-complete'
import { Route as ApiPublicPiCampaignsRouteImport } from './routes/api/public/pi-campaigns'
import { Route as ApiPublicPiBookingsRouteImport } from './routes/api/public/pi-bookings'
import { Route as ApiPublicPiBalanceRouteImport } from './routes/api/public/pi-balance'
import { Route as ApiPublicPiAuthRouteImport } from './routes/api/public/pi-auth'
import { Route as ApiPublicPiApproveRouteImport } from './routes/api/public/pi-approve'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'

const StudioDesignRoute = StudioDesignRouteImport.update({
  id: '/studio-design',
  path: '/studio-design',
  getParentRoute: () => rootRouteImport,
} as any)
const StudioRoute = StudioRouteImport.update({
  id: '/studio',
  path: '/studio',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const RfpsRoute = RfpsRouteImport.update({
  id: '/rfps',
  path: '/rfps',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnerRoute = PartnerRouteImport.update({
  id: '/partner',
  path: '/partner',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimizeRoute = OptimizeRouteImport.update({
  id: '/optimize',
  path: '/optimize',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const MarketplaceRoute = MarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsRoute = LocationsRouteImport.update({
  id: '/locations',
  path: '/locations',
  getParentRoute: () => rootRouteImport,
} as any)
const LedgerRoute = LedgerRouteImport.update({
  id: '/ledger',
  path: '/ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const InnovateRoute = InnovateRouteImport.update({
  id: '/innovate',
  path: '/innovate',
  getParentRoute: () => rootRouteImport,
} as any)
const DisplayerRoute = DisplayerRouteImport.update({
  id: '/displayer',
  path: '/displayer',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractsRoute = ContractsRouteImport.update({
  id: '/contracts',
  path: '/contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const CampaignsRoute = CampaignsRouteImport.update({
  id: '/campaigns',
  path: '/campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingsRoute = BookingsRouteImport.update({
  id: '/bookings',
  path: '/bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PartnersRegisterRoute = PartnersRegisterRouteImport.update({
  id: '/partners/register',
  path: '/partners/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LocationsSlugRoute = LocationsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => LocationsRoute,
} as any)
const GuideStadiumAdvertisingCostsRoute =
  GuideStadiumAdvertisingCostsRouteImport.update({
    id: '/guide/stadium-advertising-costs',
    path: '/guide/stadium-advertising-costs',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiInnovateFeedRoute = ApiInnovateFeedRouteImport.update({
  id: '/api/innovate-feed',
  path: '/api/innovate-feed',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateBillboardImageRoute =
  ApiGenerateBillboardImageRouteImport.update({
    id: '/api/generate-billboard-image',
    path: '/api/generate-billboard-image',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPartnersRoute = AdminPartnersRouteImport.update({
  id: '/admin/partners',
  path: '/admin/partners',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicVerifyLedgerRoute = ApiPublicVerifyLedgerRouteImport.update({
  id: '/api/public/verify-ledger',
  path: '/api/public/verify-ledger',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicScreenPlaylistRoute = ApiPublicScreenPlaylistRouteImport.update({
  id: '/api/public/screen-playlist',
  path: '/api/public/screen-playlist',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiScreensRoute = ApiPublicPiScreensRouteImport.update({
  id: '/api/public/pi-screens',
  path: '/api/public/pi-screens',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiRfpsRoute = ApiPublicPiRfpsRouteImport.update({
  id: '/api/public/pi-rfps',
  path: '/api/public/pi-rfps',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiPartnersRoute = ApiPublicPiPartnersRouteImport.update({
  id: '/api/public/pi-partners',
  path: '/api/public/pi-partners',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiOptimizeCreativeRoute =
  ApiPublicPiOptimizeCreativeRouteImport.update({
    id: '/api/public/pi-optimize-creative',
    path: '/api/public/pi-optimize-creative',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPiCreativesRoute = ApiPublicPiCreativesRouteImport.update({
  id: '/api/public/pi-creatives',
  path: '/api/public/pi-creatives',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiContractsRoute = ApiPublicPiContractsRouteImport.update({
  id: '/api/public/pi-contracts',
  path: '/api/public/pi-contracts',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiCompleteRoute = ApiPublicPiCompleteRouteImport.update({
  id: '/api/public/pi-complete',
  path: '/api/public/pi-complete',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiCampaignsRoute = ApiPublicPiCampaignsRouteImport.update({
  id: '/api/public/pi-campaigns',
  path: '/api/public/pi-campaigns',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiBookingsRoute = ApiPublicPiBookingsRouteImport.update({
  id: '/api/public/pi-bookings',
  path: '/api/public/pi-bookings',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiBalanceRoute = ApiPublicPiBalanceRouteImport.update({
  id: '/api/public/pi-balance',
  path: '/api/public/pi-balance',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiAuthRoute = ApiPublicPiAuthRouteImport.update({
  id: '/api/public/pi-auth',
  path: '/api/public/pi-auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicPiApproveRoute = ApiPublicPiApproveRouteImport.update({
  id: '/api/public/pi-approve',
  path: '/api/public/pi-approve',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/campaigns': typeof CampaignsRoute
  '/contracts': typeof ContractsRoute
  '/displayer': typeof DisplayerRoute
  '/innovate': typeof InnovateRoute
  '/ledger': typeof LedgerRoute
  '/locations': typeof LocationsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/optimize': typeof OptimizeRoute
  '/partner': typeof PartnerRoute
  '/rfps': typeof RfpsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/studio-design': typeof StudioDesignRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-billboard-image': typeof ApiGenerateBillboardImageRoute
  '/api/innovate-feed': typeof ApiInnovateFeedRoute
  '/guide/stadium-advertising-costs': typeof GuideStadiumAdvertisingCostsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/pi-approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/pi-balance': typeof ApiPublicPiBalanceRoute
  '/api/public/pi-bookings': typeof ApiPublicPiBookingsRoute
  '/api/public/pi-campaigns': typeof ApiPublicPiCampaignsRoute
  '/api/public/pi-complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi-contracts': typeof ApiPublicPiContractsRoute
  '/api/public/pi-creatives': typeof ApiPublicPiCreativesRoute
  '/api/public/pi-optimize-creative': typeof ApiPublicPiOptimizeCreativeRoute
  '/api/public/pi-partners': typeof ApiPublicPiPartnersRoute
  '/api/public/pi-rfps': typeof ApiPublicPiRfpsRoute
  '/api/public/pi-screens': typeof ApiPublicPiScreensRoute
  '/api/public/screen-playlist': typeof ApiPublicScreenPlaylistRoute
  '/api/public/verify-ledger': typeof ApiPublicVerifyLedgerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/campaigns': typeof CampaignsRoute
  '/contracts': typeof ContractsRoute
  '/displayer': typeof DisplayerRoute
  '/innovate': typeof InnovateRoute
  '/ledger': typeof LedgerRoute
  '/locations': typeof LocationsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/optimize': typeof OptimizeRoute
  '/partner': typeof PartnerRoute
  '/rfps': typeof RfpsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/studio-design': typeof StudioDesignRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-billboard-image': typeof ApiGenerateBillboardImageRoute
  '/api/innovate-feed': typeof ApiInnovateFeedRoute
  '/guide/stadium-advertising-costs': typeof GuideStadiumAdvertisingCostsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/pi-approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/pi-balance': typeof ApiPublicPiBalanceRoute
  '/api/public/pi-bookings': typeof ApiPublicPiBookingsRoute
  '/api/public/pi-campaigns': typeof ApiPublicPiCampaignsRoute
  '/api/public/pi-complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi-contracts': typeof ApiPublicPiContractsRoute
  '/api/public/pi-creatives': typeof ApiPublicPiCreativesRoute
  '/api/public/pi-optimize-creative': typeof ApiPublicPiOptimizeCreativeRoute
  '/api/public/pi-partners': typeof ApiPublicPiPartnersRoute
  '/api/public/pi-rfps': typeof ApiPublicPiRfpsRoute
  '/api/public/pi-screens': typeof ApiPublicPiScreensRoute
  '/api/public/screen-playlist': typeof ApiPublicScreenPlaylistRoute
  '/api/public/verify-ledger': typeof ApiPublicVerifyLedgerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/bookings': typeof BookingsRoute
  '/campaigns': typeof CampaignsRoute
  '/contracts': typeof ContractsRoute
  '/displayer': typeof DisplayerRoute
  '/innovate': typeof InnovateRoute
  '/ledger': typeof LedgerRoute
  '/locations': typeof LocationsRouteWithChildren
  '/marketplace': typeof MarketplaceRoute
  '/mcp': typeof McpRoute
  '/optimize': typeof OptimizeRoute
  '/partner': typeof PartnerRoute
  '/rfps': typeof RfpsRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/studio': typeof StudioRoute
  '/studio-design': typeof StudioDesignRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/admin/partners': typeof AdminPartnersRoute
  '/api/chat': typeof ApiChatRoute
  '/api/generate-billboard-image': typeof ApiGenerateBillboardImageRoute
  '/api/innovate-feed': typeof ApiInnovateFeedRoute
  '/guide/stadium-advertising-costs': typeof GuideStadiumAdvertisingCostsRoute
  '/locations/$slug': typeof LocationsSlugRoute
  '/partners/register': typeof PartnersRegisterRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/api/public/pi-approve': typeof ApiPublicPiApproveRoute
  '/api/public/pi-auth': typeof ApiPublicPiAuthRoute
  '/api/public/pi-balance': typeof ApiPublicPiBalanceRoute
  '/api/public/pi-bookings': typeof ApiPublicPiBookingsRoute
  '/api/public/pi-campaigns': typeof ApiPublicPiCampaignsRoute
  '/api/public/pi-complete': typeof ApiPublicPiCompleteRoute
  '/api/public/pi-contracts': typeof ApiPublicPiContractsRoute
  '/api/public/pi-creatives': typeof ApiPublicPiCreativesRoute
  '/api/public/pi-optimize-creative': typeof ApiPublicPiOptimizeCreativeRoute
  '/api/public/pi-partners': typeof ApiPublicPiPartnersRoute
  '/api/public/pi-rfps': typeof ApiPublicPiRfpsRoute
  '/api/public/pi-screens': typeof ApiPublicPiScreensRoute
  '/api/public/screen-playlist': typeof ApiPublicScreenPlaylistRoute
  '/api/public/verify-ledger': typeof ApiPublicVerifyLedgerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/bookings'
    | '/campaigns'
    | '/contracts'
    | '/displayer'
    | '/innovate'
    | '/ledger'
    | '/locations'
    | '/marketplace'
    | '/mcp'
    | '/optimize'
    | '/partner'
    | '/rfps'
    | '/sitemap.xml'
    | '/studio'
    | '/studio-design'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/partners'
    | '/api/chat'
    | '/api/generate-billboard-image'
    | '/api/innovate-feed'
    | '/guide/stadium-advertising-costs'
    | '/locations/$slug'
    | '/partners/register'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/pi-approve'
    | '/api/public/pi-auth'
    | '/api/public/pi-balance'
    | '/api/public/pi-bookings'
    | '/api/public/pi-campaigns'
    | '/api/public/pi-complete'
    | '/api/public/pi-contracts'
    | '/api/public/pi-creatives'
    | '/api/public/pi-optimize-creative'
    | '/api/public/pi-partners'
    | '/api/public/pi-rfps'
    | '/api/public/pi-screens'
    | '/api/public/screen-playlist'
    | '/api/public/verify-ledger'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/bookings'
    | '/campaigns'
    | '/contracts'
    | '/displayer'
    | '/innovate'
    | '/ledger'
    | '/locations'
    | '/marketplace'
    | '/mcp'
    | '/optimize'
    | '/partner'
    | '/rfps'
    | '/sitemap.xml'
    | '/studio'
    | '/studio-design'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/partners'
    | '/api/chat'
    | '/api/generate-billboard-image'
    | '/api/innovate-feed'
    | '/guide/stadium-advertising-costs'
    | '/locations/$slug'
    | '/partners/register'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/pi-approve'
    | '/api/public/pi-auth'
    | '/api/public/pi-balance'
    | '/api/public/pi-bookings'
    | '/api/public/pi-campaigns'
    | '/api/public/pi-complete'
    | '/api/public/pi-contracts'
    | '/api/public/pi-creatives'
    | '/api/public/pi-optimize-creative'
    | '/api/public/pi-partners'
    | '/api/public/pi-rfps'
    | '/api/public/pi-screens'
    | '/api/public/screen-playlist'
    | '/api/public/verify-ledger'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/bookings'
    | '/campaigns'
    | '/contracts'
    | '/displayer'
    | '/innovate'
    | '/ledger'
    | '/locations'
    | '/marketplace'
    | '/mcp'
    | '/optimize'
    | '/partner'
    | '/rfps'
    | '/sitemap.xml'
    | '/studio'
    | '/studio-design'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/admin/partners'
    | '/api/chat'
    | '/api/generate-billboard-image'
    | '/api/innovate-feed'
    | '/guide/stadium-advertising-costs'
    | '/locations/$slug'
    | '/partners/register'
    | '/.mcp/invoke-tool/$tool'
    | '/api/public/pi-approve'
    | '/api/public/pi-auth'
    | '/api/public/pi-balance'
    | '/api/public/pi-bookings'
    | '/api/public/pi-campaigns'
    | '/api/public/pi-complete'
    | '/api/public/pi-contracts'
    | '/api/public/pi-creatives'
    | '/api/public/pi-optimize-creative'
    | '/api/public/pi-partners'
    | '/api/public/pi-rfps'
    | '/api/public/pi-screens'
    | '/api/public/screen-playlist'
    | '/api/public/verify-ledger'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  BookingsRoute: typeof BookingsRoute
  CampaignsRoute: typeof CampaignsRoute
  ContractsRoute: typeof ContractsRoute
  DisplayerRoute: typeof DisplayerRoute
  InnovateRoute: typeof InnovateRoute
  LedgerRoute: typeof LedgerRoute
  LocationsRoute: typeof LocationsRouteWithChildren
  MarketplaceRoute: typeof MarketplaceRoute
  McpRoute: typeof McpRoute
  OptimizeRoute: typeof OptimizeRoute
  PartnerRoute: typeof PartnerRoute
  RfpsRoute: typeof RfpsRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  StudioRoute: typeof StudioRoute
  StudioDesignRoute: typeof StudioDesignRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  AdminPartnersRoute: typeof AdminPartnersRoute
  ApiChatRoute: typeof ApiChatRoute
  ApiGenerateBillboardImageRoute: typeof ApiGenerateBillboardImageRoute
  ApiInnovateFeedRoute: typeof ApiInnovateFeedRoute
  GuideStadiumAdvertisingCostsRoute: typeof GuideStadiumAdvertisingCostsRoute
  PartnersRegisterRoute: typeof PartnersRegisterRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicPiApproveRoute: typeof ApiPublicPiApproveRoute
  ApiPublicPiAuthRoute: typeof ApiPublicPiAuthRoute
  ApiPublicPiBalanceRoute: typeof ApiPublicPiBalanceRoute
  ApiPublicPiBookingsRoute: typeof ApiPublicPiBookingsRoute
  ApiPublicPiCampaignsRoute: typeof ApiPublicPiCampaignsRoute
  ApiPublicPiCompleteRoute: typeof ApiPublicPiCompleteRoute
  ApiPublicPiContractsRoute: typeof ApiPublicPiContractsRoute
  ApiPublicPiCreativesRoute: typeof ApiPublicPiCreativesRoute
  ApiPublicPiOptimizeCreativeRoute: typeof ApiPublicPiOptimizeCreativeRoute
  ApiPublicPiPartnersRoute: typeof ApiPublicPiPartnersRoute
  ApiPublicPiRfpsRoute: typeof ApiPublicPiRfpsRoute
  ApiPublicPiScreensRoute: typeof ApiPublicPiScreensRoute
  ApiPublicScreenPlaylistRoute: typeof ApiPublicScreenPlaylistRoute
  ApiPublicVerifyLedgerRoute: typeof ApiPublicVerifyLedgerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/studio-design': {
      id: '/studio-design'
      path: '/studio-design'
      fullPath: '/studio-design'
      preLoaderRoute: typeof StudioDesignRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/studio': {
      id: '/studio'
      path: '/studio'
      fullPath: '/studio'
      preLoaderRoute: typeof StudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rfps': {
      id: '/rfps'
      path: '/rfps'
      fullPath: '/rfps'
      preLoaderRoute: typeof RfpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partner': {
      id: '/partner'
      path: '/partner'
      fullPath: '/partner'
      preLoaderRoute: typeof PartnerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimize': {
      id: '/optimize'
      path: '/optimize'
      fullPath: '/optimize'
      preLoaderRoute: typeof OptimizeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/marketplace': {
      id: '/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof MarketplaceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations': {
      id: '/locations'
      path: '/locations'
      fullPath: '/locations'
      preLoaderRoute: typeof LocationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ledger': {
      id: '/ledger'
      path: '/ledger'
      fullPath: '/ledger'
      preLoaderRoute: typeof LedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/innovate': {
      id: '/innovate'
      path: '/innovate'
      fullPath: '/innovate'
      preLoaderRoute: typeof InnovateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/displayer': {
      id: '/displayer'
      path: '/displayer'
      fullPath: '/displayer'
      preLoaderRoute: typeof DisplayerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contracts': {
      id: '/contracts'
      path: '/contracts'
      fullPath: '/contracts'
      preLoaderRoute: typeof ContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/campaigns': {
      id: '/campaigns'
      path: '/campaigns'
      fullPath: '/campaigns'
      preLoaderRoute: typeof CampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bookings': {
      id: '/bookings'
      path: '/bookings'
      fullPath: '/bookings'
      preLoaderRoute: typeof BookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/partners/register': {
      id: '/partners/register'
      path: '/partners/register'
      fullPath: '/partners/register'
      preLoaderRoute: typeof PartnersRegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/locations/$slug': {
      id: '/locations/$slug'
      path: '/$slug'
      fullPath: '/locations/$slug'
      preLoaderRoute: typeof LocationsSlugRouteImport
      parentRoute: typeof LocationsRoute
    }
    '/guide/stadium-advertising-costs': {
      id: '/guide/stadium-advertising-costs'
      path: '/guide/stadium-advertising-costs'
      fullPath: '/guide/stadium-advertising-costs'
      preLoaderRoute: typeof GuideStadiumAdvertisingCostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/innovate-feed': {
      id: '/api/innovate-feed'
      path: '/api/innovate-feed'
      fullPath: '/api/innovate-feed'
      preLoaderRoute: typeof ApiInnovateFeedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate-billboard-image': {
      id: '/api/generate-billboard-image'
      path: '/api/generate-billboard-image'
      fullPath: '/api/generate-billboard-image'
      preLoaderRoute: typeof ApiGenerateBillboardImageRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/partners': {
      id: '/admin/partners'
      path: '/admin/partners'
      fullPath: '/admin/partners'
      preLoaderRoute: typeof AdminPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/verify-ledger': {
      id: '/api/public/verify-ledger'
      path: '/api/public/verify-ledger'
      fullPath: '/api/public/verify-ledger'
      preLoaderRoute: typeof ApiPublicVerifyLedgerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/screen-playlist': {
      id: '/api/public/screen-playlist'
      path: '/api/public/screen-playlist'
      fullPath: '/api/public/screen-playlist'
      preLoaderRoute: typeof ApiPublicScreenPlaylistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-screens': {
      id: '/api/public/pi-screens'
      path: '/api/public/pi-screens'
      fullPath: '/api/public/pi-screens'
      preLoaderRoute: typeof ApiPublicPiScreensRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-rfps': {
      id: '/api/public/pi-rfps'
      path: '/api/public/pi-rfps'
      fullPath: '/api/public/pi-rfps'
      preLoaderRoute: typeof ApiPublicPiRfpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-partners': {
      id: '/api/public/pi-partners'
      path: '/api/public/pi-partners'
      fullPath: '/api/public/pi-partners'
      preLoaderRoute: typeof ApiPublicPiPartnersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-optimize-creative': {
      id: '/api/public/pi-optimize-creative'
      path: '/api/public/pi-optimize-creative'
      fullPath: '/api/public/pi-optimize-creative'
      preLoaderRoute: typeof ApiPublicPiOptimizeCreativeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-creatives': {
      id: '/api/public/pi-creatives'
      path: '/api/public/pi-creatives'
      fullPath: '/api/public/pi-creatives'
      preLoaderRoute: typeof ApiPublicPiCreativesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-contracts': {
      id: '/api/public/pi-contracts'
      path: '/api/public/pi-contracts'
      fullPath: '/api/public/pi-contracts'
      preLoaderRoute: typeof ApiPublicPiContractsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-complete': {
      id: '/api/public/pi-complete'
      path: '/api/public/pi-complete'
      fullPath: '/api/public/pi-complete'
      preLoaderRoute: typeof ApiPublicPiCompleteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-campaigns': {
      id: '/api/public/pi-campaigns'
      path: '/api/public/pi-campaigns'
      fullPath: '/api/public/pi-campaigns'
      preLoaderRoute: typeof ApiPublicPiCampaignsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-bookings': {
      id: '/api/public/pi-bookings'
      path: '/api/public/pi-bookings'
      fullPath: '/api/public/pi-bookings'
      preLoaderRoute: typeof ApiPublicPiBookingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-balance': {
      id: '/api/public/pi-balance'
      path: '/api/public/pi-balance'
      fullPath: '/api/public/pi-balance'
      preLoaderRoute: typeof ApiPublicPiBalanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-auth': {
      id: '/api/public/pi-auth'
      path: '/api/public/pi-auth'
      fullPath: '/api/public/pi-auth'
      preLoaderRoute: typeof ApiPublicPiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/pi-approve': {
      id: '/api/public/pi-approve'
      path: '/api/public/pi-approve'
      fullPath: '/api/public/pi-approve'
      preLoaderRoute: typeof ApiPublicPiApproveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface LocationsRouteChildren {
  LocationsSlugRoute: typeof LocationsSlugRoute
}

const LocationsRouteChildren: LocationsRouteChildren = {
  LocationsSlugRoute: LocationsSlugRoute,
}

const LocationsRouteWithChildren = LocationsRoute._addFileChildren(
  LocationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  BookingsRoute: BookingsRoute,
  CampaignsRoute: CampaignsRoute,
  ContractsRoute: ContractsRoute,
  DisplayerRoute: DisplayerRoute,
  InnovateRoute: InnovateRoute,
  LedgerRoute: LedgerRoute,
  LocationsRoute: LocationsRouteWithChildren,
  MarketplaceRoute: MarketplaceRoute,
  McpRoute: McpRoute,
  OptimizeRoute: OptimizeRoute,
  PartnerRoute: PartnerRoute,
  RfpsRoute: RfpsRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  StudioRoute: StudioRoute,
  StudioDesignRoute: StudioDesignRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  AdminPartnersRoute: AdminPartnersRoute,
  ApiChatRoute: ApiChatRoute,
  ApiGenerateBillboardImageRoute: ApiGenerateBillboardImageRoute,
  ApiInnovateFeedRoute: ApiInnovateFeedRoute,
  GuideStadiumAdvertisingCostsRoute: GuideStadiumAdvertisingCostsRoute,
  PartnersRegisterRoute: PartnersRegisterRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicPiApproveRoute: ApiPublicPiApproveRoute,
  ApiPublicPiAuthRoute: ApiPublicPiAuthRoute,
  ApiPublicPiBalanceRoute: ApiPublicPiBalanceRoute,
  ApiPublicPiBookingsRoute: ApiPublicPiBookingsRoute,
  ApiPublicPiCampaignsRoute: ApiPublicPiCampaignsRoute,
  ApiPublicPiCompleteRoute: ApiPublicPiCompleteRoute,
  ApiPublicPiContractsRoute: ApiPublicPiContractsRoute,
  ApiPublicPiCreativesRoute: ApiPublicPiCreativesRoute,
  ApiPublicPiOptimizeCreativeRoute: ApiPublicPiOptimizeCreativeRoute,
  ApiPublicPiPartnersRoute: ApiPublicPiPartnersRoute,
  ApiPublicPiRfpsRoute: ApiPublicPiRfpsRoute,
  ApiPublicPiScreensRoute: ApiPublicPiScreensRoute,
  ApiPublicScreenPlaylistRoute: ApiPublicScreenPlaylistRoute,
  ApiPublicVerifyLedgerRoute: ApiPublicVerifyLedgerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
